site_name: Botlib
repo_url: https://github.com/Mauricio-Furlan/botlib
repo_name: Botlib
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/robo.png
  favicon: assets/robo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [actions]